### ISSUE TITLE
Double check everything so that no sensitive data is left in any of the repos

### ISSUE THREAD

**Issue by Stolarskis** [Stolarskis/flood-alert-app#1]

**Comment by Stolarskis** [comment]
There was a couple phone numbers left. But thats it.

**Comment by tcraxs** [comment]
@Stolarskis pls have a look at your files here:
* flood-alert-app/src/build/terraform/projects/flood-alert/terraform.tfstate
* flood-alert-app/src/build/terraform/projects/flood-alert/terraform.tfstate.backup

**Comment by Stolarskis** [comment]
Thanks my man, I was working on a different branch and I must have committed it accidentally.
