### ISSUE TITLE
Add mute alert status to grpc call

### ISSUE THREAD

**Issue by stevenaldinger** [Stolarskis/flood-alert-app#6]
In [src/api/flood-app-api.proto](https://github.com/Stolarskis/flood-alert-app/blob/master/src/api/flood-app-api.proto) where muteAlertStatus = `true` for muted and `false` for not or however you want to handle it
```
//Mute SMS = "SMS"
//Mute Email = "Email"
message muteAlertRequest{
  string muteAlertType = 1;
  bool muteAlertStatus = 2;
}
```

**Comment by Stolarskis** [comment]
Good point, I can see how toggling would causing some issues.

**Comment by Stolarskis** [comment]
Api + client/server have been updated. Thanks again!
